site_name: Sourcey

repo_name: tianheg/sourcey
repo_url: https://github.com/tianheg/sourcey/
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 科学爱好者周刊:
    - 最新一期: ruanyf-weekly/issue-239.md
    - 238: ruanyf-weekly/issue-238.md
    - 237: ruanyf-weekly/issue-237.md
    - 236: ruanyf-weekly/issue-236.md
    - 235: ruanyf-weekly/issue-235.md
    - 234: ruanyf-weekly/issue-234.md
    - 233: ruanyf-weekly/issue-233.md
    - 232: ruanyf-weekly/issue-232.md
    - 231: ruanyf-weekly/issue-231.md
    - 230: ruanyf-weekly/issue-230.md
    - 229: ruanyf-weekly/issue-229.md
    - 228: ruanyf-weekly/issue-228.md
    - 227: ruanyf-weekly/issue-227.md
    - 226: ruanyf-weekly/issue-226.md
    - 225: ruanyf-weekly/issue-225.md
    - 224: ruanyf-weekly/issue-224.md
    - 223: ruanyf-weekly/issue-223.md
    - 222: ruanyf-weekly/issue-222.md
    - 221: ruanyf-weekly/issue-221.md
    - 220: ruanyf-weekly/issue-220.md
    - 219: ruanyf-weekly/issue-219.md
    - 218: ruanyf-weekly/issue-218.md
    - 217: ruanyf-weekly/issue-217.md
    - 216: ruanyf-weekly/issue-216.md
    - 215: ruanyf-weekly/issue-215.md
    - 214: ruanyf-weekly/issue-214.md
    - 213: ruanyf-weekly/issue-213.md
    - 212: ruanyf-weekly/issue-212.md
    - 211: ruanyf-weekly/issue-211.md
    - 210: ruanyf-weekly/issue-210.md
    - 209: ruanyf-weekly/issue-209.md
    - 208: ruanyf-weekly/issue-208.md
    - 207: ruanyf-weekly/issue-207.md
    - 206: ruanyf-weekly/issue-206.md
    - 205: ruanyf-weekly/issue-205.md
    - 204: ruanyf-weekly/issue-204.md
    - 203: ruanyf-weekly/issue-203.md
    - 202: ruanyf-weekly/issue-202.md
    - 201: ruanyf-weekly/issue-201.md
    - 200: ruanyf-weekly/issue-200.md
    - 199: ruanyf-weekly/issue-199.md
    - 198: ruanyf-weekly/issue-198.md
    - 197: ruanyf-weekly/issue-197.md
    - 196: ruanyf-weekly/issue-196.md
    - 195: ruanyf-weekly/issue-195.md
    - 194: ruanyf-weekly/issue-194.md
    - 193: ruanyf-weekly/issue-193.md
    - 192: ruanyf-weekly/issue-192.md
    - 191: ruanyf-weekly/issue-191.md
    - 190: ruanyf-weekly/issue-190.md
    - 189: ruanyf-weekly/issue-189.md
    - 188: ruanyf-weekly/issue-188.md
    - 187: ruanyf-weekly/issue-187.md
    - 186: ruanyf-weekly/issue-186.md
    - 185: ruanyf-weekly/issue-185.md
    - 184: ruanyf-weekly/issue-184.md
    - 183: ruanyf-weekly/issue-183.md
    - 182: ruanyf-weekly/issue-182.md
    - 181: ruanyf-weekly/issue-181.md
    - 180: ruanyf-weekly/issue-180.md
    - 179: ruanyf-weekly/issue-179.md
    - 178: ruanyf-weekly/issue-178.md
    - 177: ruanyf-weekly/issue-177.md
    - 176: ruanyf-weekly/issue-176.md
    - 175: ruanyf-weekly/issue-175.md
    - 174: ruanyf-weekly/issue-174.md
    - 173: ruanyf-weekly/issue-173.md
    - 172: ruanyf-weekly/issue-172.md
    - 171: ruanyf-weekly/issue-171.md
    - 170: ruanyf-weekly/issue-170.md
    - 169: ruanyf-weekly/issue-169.md
    - 168: ruanyf-weekly/issue-168.md
    - 167: ruanyf-weekly/issue-167.md
    - 166: ruanyf-weekly/issue-166.md
    - 165: ruanyf-weekly/issue-165.md
    - 164: ruanyf-weekly/issue-164.md
    - 163: ruanyf-weekly/issue-163.md
    - 162: ruanyf-weekly/issue-162.md
    - 161: ruanyf-weekly/issue-161.md
    - 160: ruanyf-weekly/issue-160.md
    - 159: ruanyf-weekly/issue-159.md
    - 158: ruanyf-weekly/issue-158.md
    - 157: ruanyf-weekly/issue-157.md
    - 156: ruanyf-weekly/issue-156.md
    - 155: ruanyf-weekly/issue-155.md
    - 154: ruanyf-weekly/issue-154.md
    - 153: ruanyf-weekly/issue-153.md
    - 152: ruanyf-weekly/issue-152.md
    - 151: ruanyf-weekly/issue-151.md
    - 150: ruanyf-weekly/issue-150.md
    - 149: ruanyf-weekly/issue-149.md
    - 148: ruanyf-weekly/issue-148.md
    - 147: ruanyf-weekly/issue-147.md
    - 146: ruanyf-weekly/issue-146.md
    - 145: ruanyf-weekly/issue-145.md
    - 144: ruanyf-weekly/issue-144.md
    - 143: ruanyf-weekly/issue-143.md
    - 142: ruanyf-weekly/issue-142.md
    - 141: ruanyf-weekly/issue-141.md
    - 140: ruanyf-weekly/issue-140.md
    - 139: ruanyf-weekly/issue-139.md
    - 138: ruanyf-weekly/issue-138.md
    - 137: ruanyf-weekly/issue-137.md
    - 136: ruanyf-weekly/issue-136.md
    - 135: ruanyf-weekly/issue-135.md
    - 134: ruanyf-weekly/issue-134.md
    - 133: ruanyf-weekly/issue-133.md
    - 132: ruanyf-weekly/issue-132.md
    - 131: ruanyf-weekly/issue-131.md
    - 130: ruanyf-weekly/issue-130.md
    - 129: ruanyf-weekly/issue-129.md
    - 128: ruanyf-weekly/issue-128.md
    - 127: ruanyf-weekly/issue-127.md
    - 126: ruanyf-weekly/issue-126.md
    - 125: ruanyf-weekly/issue-125.md
    - 124: ruanyf-weekly/issue-124.md
    - 123: ruanyf-weekly/issue-123.md
    - 122: ruanyf-weekly/issue-122.md
    - 121: ruanyf-weekly/issue-121.md
    - 120: ruanyf-weekly/issue-120.md
    - 119: ruanyf-weekly/issue-119.md
    - 118: ruanyf-weekly/issue-118.md
    - 117: ruanyf-weekly/issue-117.md
    - 116: ruanyf-weekly/issue-116.md
    - 115: ruanyf-weekly/issue-115.md
    - 114: ruanyf-weekly/issue-114.md
    - 113: ruanyf-weekly/issue-113.md
    - 112: ruanyf-weekly/issue-112.md
    - 111: ruanyf-weekly/issue-111.md
    - 110: ruanyf-weekly/issue-110.md
    - 109: ruanyf-weekly/issue-109.md
    - 108: ruanyf-weekly/issue-108.md
    - 107: ruanyf-weekly/issue-107.md
    - 106: ruanyf-weekly/issue-106.md
    - 105: ruanyf-weekly/issue-105.md
    - 104: ruanyf-weekly/issue-104.md
    - 103: ruanyf-weekly/issue-103.md
    - 102: ruanyf-weekly/issue-102.md
    - 101: ruanyf-weekly/issue-101.md
    - 100: ruanyf-weekly/issue-100.md
    - 99: ruanyf-weekly/issue-99.md
    - 98: ruanyf-weekly/issue-98.md
    - 97: ruanyf-weekly/issue-97.md
    - 96: ruanyf-weekly/issue-96.md
    - 95: ruanyf-weekly/issue-95.md
    - 94: ruanyf-weekly/issue-94.md
    - 93: ruanyf-weekly/issue-93.md
    - 92: ruanyf-weekly/issue-92.md
    - 91: ruanyf-weekly/issue-91.md
    - 90: ruanyf-weekly/issue-90.md
    - 89: ruanyf-weekly/issue-89.md
    - 88: ruanyf-weekly/issue-88.md
    - 87: ruanyf-weekly/issue-87.md
    - 86: ruanyf-weekly/issue-86.md
    - 85: ruanyf-weekly/issue-85.md
    - 84: ruanyf-weekly/issue-84.md
    - 83: ruanyf-weekly/issue-83.md
    - 82: ruanyf-weekly/issue-82.md
    - 81: ruanyf-weekly/issue-81.md
    - 80: ruanyf-weekly/issue-80.md
    - 79: ruanyf-weekly/issue-79.md
    - 78: ruanyf-weekly/issue-78.md
    - 77: ruanyf-weekly/issue-77.md
    - 76: ruanyf-weekly/issue-76.md
    - 75: ruanyf-weekly/issue-75.md
    - 74: ruanyf-weekly/issue-74.md
    - 73: ruanyf-weekly/issue-73.md
    - 72: ruanyf-weekly/issue-72.md
    - 71: ruanyf-weekly/issue-71.md
    - 70: ruanyf-weekly/issue-70.md
    - 69: ruanyf-weekly/issue-69.md
    - 68: ruanyf-weekly/issue-68.md
    - 67: ruanyf-weekly/issue-67.md
    - 66: ruanyf-weekly/issue-66.md
    - 65: ruanyf-weekly/issue-65.md
    - 64: ruanyf-weekly/issue-64.md
    - 63: ruanyf-weekly/issue-63.md
    - 62: ruanyf-weekly/issue-62.md
    - 61: ruanyf-weekly/issue-61.md
    - 60: ruanyf-weekly/issue-60.md
    - 59: ruanyf-weekly/issue-59.md
    - 58: ruanyf-weekly/issue-58.md
    - 57: ruanyf-weekly/issue-57.md
    - 56: ruanyf-weekly/issue-56.md
    - 55: ruanyf-weekly/issue-55.md
    - 54: ruanyf-weekly/issue-54.md
    - 53: ruanyf-weekly/issue-53.md
    - 52: ruanyf-weekly/issue-52.md
    - 51: ruanyf-weekly/issue-51.md
    - 50: ruanyf-weekly/issue-50.md
    - 49: ruanyf-weekly/issue-49.md
    - 48: ruanyf-weekly/issue-48.md
    - 47: ruanyf-weekly/issue-47.md
    - 46: ruanyf-weekly/issue-46.md
    - 45: ruanyf-weekly/issue-45.md
    - 44: ruanyf-weekly/issue-44.md
    - 43: ruanyf-weekly/issue-43.md
    - 42: ruanyf-weekly/issue-42.md
    - 41: ruanyf-weekly/issue-41.md
    - 40: ruanyf-weekly/issue-40.md
    - 39: ruanyf-weekly/issue-39.md
    - 38: ruanyf-weekly/issue-38.md
    - 37: ruanyf-weekly/issue-37.md
    - 36: ruanyf-weekly/issue-36.md
    - 35: ruanyf-weekly/issue-35.md
    - 34: ruanyf-weekly/issue-34.md
    - 33: ruanyf-weekly/issue-33.md
    - 32: ruanyf-weekly/issue-32.md
    - 31: ruanyf-weekly/issue-31.md
    - 30: ruanyf-weekly/issue-30.md
    - 29: ruanyf-weekly/issue-29.md
    - 28: ruanyf-weekly/issue-28.md
    - 27: ruanyf-weekly/issue-27.md
    - 26: ruanyf-weekly/issue-26.md
    - 25: ruanyf-weekly/issue-25.md
    - 24: ruanyf-weekly/issue-24.md
    - 23: ruanyf-weekly/issue-23.md
    - 22: ruanyf-weekly/issue-22.md
    - 21: ruanyf-weekly/issue-21.md
    - 20: ruanyf-weekly/issue-20.md
    - 19: ruanyf-weekly/issue-19.md
    - 18: ruanyf-weekly/issue-18.md
    - 17: ruanyf-weekly/issue-17.md
    - 16: ruanyf-weekly/issue-16.md
    - 15: ruanyf-weekly/issue-15.md
    - 14: ruanyf-weekly/issue-14.md
    - 13: ruanyf-weekly/issue-13.md
    - 12: ruanyf-weekly/issue-12.md
    - 11: ruanyf-weekly/issue-11.md
    - 10: ruanyf-weekly/issue-10.md
    - 9: ruanyf-weekly/issue-9.md
    - 8: ruanyf-weekly/issue-8.md
    - 7: ruanyf-weekly/issue-7.md
    - 6: ruanyf-weekly/issue-6.md
    - 5: ruanyf-weekly/issue-5.md
    - 4: ruanyf-weekly/issue-4.md
    - 3: ruanyf-weekly/issue-3.md
    - 2: ruanyf-weekly/issue-2.md
    - 1: ruanyf-weekly/issue-1.md

  - "Hello GitHub":
    - 最新一期: hello-github/HelloGitHub81.md
    - 80: hello-github/HelloGitHub80.md
    - 79: hello-github/HelloGitHub79.md
    - 78: hello-github/HelloGitHub78.md
    - 77: hello-github/HelloGitHub77.md
    - 76: hello-github/HelloGitHub76.md
    - 75: hello-github/HelloGitHub75.md
    - 74: hello-github/HelloGitHub74.md
    - 73: hello-github/HelloGitHub73.md
    - 72: hello-github/HelloGitHub72.md
    - 71: hello-github/HelloGitHub71.md
    - 70: hello-github/HelloGitHub70.md
    - 69: hello-github/HelloGitHub69.md
    - 68: hello-github/HelloGitHub68.md
    - 67: hello-github/HelloGitHub67.md
    - 66: hello-github/HelloGitHub66.md
    - 65: hello-github/HelloGitHub65.md
    - 64: hello-github/HelloGitHub64.md
    - 63: hello-github/HelloGitHub63.md
    - 62: hello-github/HelloGitHub62.md
    - 61: hello-github/HelloGitHub61.md
    - 60: hello-github/HelloGitHub60.md
    - 59: hello-github/HelloGitHub59.md
    - 58: hello-github/HelloGitHub58.md
    - 57: hello-github/HelloGitHub57.md
    - 56: hello-github/HelloGitHub56.md
    - 55: hello-github/HelloGitHub55.md
    - 54: hello-github/HelloGitHub54.md
    - 53: hello-github/HelloGitHub53.md
    - 52: hello-github/HelloGitHub52.md
    - 51: hello-github/HelloGitHub51.md
    - 50: hello-github/HelloGitHub50.md
    - 49: hello-github/HelloGitHub49.md
    - 48: hello-github/HelloGitHub48.md
    - 47: hello-github/HelloGitHub47.md
    - 46: hello-github/HelloGitHub46.md
    - 45: hello-github/HelloGitHub45.md
    - 44: hello-github/HelloGitHub44.md
    - 43: hello-github/HelloGitHub43.md
    - 42: hello-github/HelloGitHub42.md
    - 41: hello-github/HelloGitHub41.md
    - 40: hello-github/HelloGitHub40.md
    - 39: hello-github/HelloGitHub39.md
    - 38: hello-github/HelloGitHub38.md
    - 37: hello-github/HelloGitHub37.md
    - 36: hello-github/HelloGitHub36.md
    - 35: hello-github/HelloGitHub35.md
    - 34: hello-github/HelloGitHub34.md
    - 33: hello-github/HelloGitHub33.md
    - 32: hello-github/HelloGitHub32.md
    - 31: hello-github/HelloGitHub31.md
    - 30: hello-github/HelloGitHub30.md
    - 29: hello-github/HelloGitHub29.md
    - 28: hello-github/HelloGitHub28.md
    - 27: hello-github/HelloGitHub27.md
    - 26: hello-github/HelloGitHub26.md
    - 25: hello-github/HelloGitHub25.md
    - 24: hello-github/HelloGitHub24.md
    - 23: hello-github/HelloGitHub23.md
    - 22: hello-github/HelloGitHub22.md
    - 21: hello-github/HelloGitHub21.md
    - 20: hello-github/HelloGitHub20.md
    - 19: hello-github/HelloGitHub19.md
    - 18: hello-github/HelloGitHub18.md
    - 17: hello-github/HelloGitHub17.md
    - 16: hello-github/HelloGitHub16.md
    - 15: hello-github/HelloGitHub15.md
    - 14: hello-github/HelloGitHub14.md
    - 13: hello-github/HelloGitHub13.md
    - 12: hello-github/HelloGitHub12.md
    - 11: hello-github/HelloGitHub11.md
    - 10: hello-github/HelloGitHub10.md
    - 9: hello-github/HelloGitHub09.md
    - 8: hello-github/HelloGitHub08.md
    - 7: hello-github/HelloGitHub07.md
    - 6: hello-github/HelloGitHub06.md
    - 5: hello-github/HelloGitHub05.md
    - 4: hello-github/HelloGitHub04.md
    - 3: hello-github/HelloGitHub03.md
    - 2: hello-github/HelloGitHub02.md
    - 1: hello-github/HelloGitHub01.md
